version: "3.9"
services:
  db:
    image: postgres:11-alpine
    env_file:
      - .env_db
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    env_file:
      - .env_wiki
    restart: unless-stopped
    ports:
      - "3000:3000"

volumes:
  db-data:
